### ISSUE TITLE
HQ-50K error

### ISSUE THREAD

**Issue by yuweics** [littleYaang/HQ-50K#1]
pyarrow.lib.ArrowInvalid: CSV parse error: Expected 1 columns, got 4: https://www.gannett-cdn.com/presto/2018/07/21/PCHI/8b111386-71f8-4eab-9691-7d53cb6c3f2e-_GO_7349 ...

**Comment by yongliuy** [comment]
> pyarrow.lib.ArrowInvalid: CSV parse error: Expected 1 columns, got 4: https://www.gannett-cdn.com/presto/2018/07/21/PCHI/8b111386-71f8-4eab-9691-7d53cb6c3f2e-_GO_7349 ...

Hello~
Have you solved it? I had the same problem while downloading.

**Comment by littleYaang** [comment]
Thanks for the questions, the error occurs because the default delimiter appears in our urls, so you can refer to the [scripts](https://github.com/littleYaang/HQ-50K/tree/main/data_preprocess) to modify the source code of img2dataset to solve it.

**Comment by yongliuy** [comment]
> Thanks for the questions, the error occurs because the default delimiter appears in our urls, so you can refer to the [scripts](https://github.com/littleYaang/HQ-50K/tree/main/data_preprocess) to modify the source code of img2dataset to solve it.

Hello~
Some of the images I get after downloading are always thumbnails instead of original images. I found that these images come from https://i.postimg.cc(from line 47539 in all.txt). How should I avoid this problem?

**Comment by Aitical** [comment]
I've encountered a similar issue with the Img2dataset download process, with numerous data files returning download errors.

For quickly obtain and study the proposed HQ-50K dataset, if it would be possible for you to share the complete dataset with me through an online drive, such as Google Drive or Baidu YunPan. My email is gwu@hit.edu.cn. 

I sincerely appreciate your assistance and look forward to your response. Thank you in advance.

**Comment by knsong** [comment]
> I've encountered a similar issue with the Img2dataset download process, with numerous data files returning download errors.
> 
> For quickly obtain and study the proposed HQ-50K dataset, if it would be possible for you to share the complete dataset with me through an online drive, such as Google Drive or Baidu YunPan. My email is [gwu@hit.edu.cn](mailto:gwu@hit.edu.cn).
> 
> I sincerely appreciate your assistance and look forward to your response. Thank you in advance.

Do you have the complete dataset on an online drive now ?

**Comment by littleYaang** [comment]
We also release the alternative way to get the whole , we provide [alternative ways](https://github.com/littleYaang/HQ-50K/blob/main/data_preprocess/README.md) for dataset download.
