### ISSUE TITLE
Fail to get dataset using azcopy method

### ISSUE THREAD

**Issue by VanesYg** [littleYaang/HQ-50K#5]
Hi, thanks for your sharing. But I met a problem when I tried to get the dataset by azcopy. 
Here's my command and the error message:

`./azcopy copy "https://interndatasetsv2.blob.core.windows.net/laion-hr/HQ-50K/TRAIN_BICUBIC/?sv=2021-08-06&st=2023-11-03T06%3A05%3A22Z&se=2031-12-04T06%3A05%3A00Z&sr=c&sp=rl&sig=XlgPo%2FN4EQFFYVUReeCFxKQ5VwRExwFeLuFbZtAP2Zo%3D" "/home/work/HQ-50K/dataset/" --recursive=true `

```

INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason HEAD https://interndatasetsv2.blob.core.windows.net/laion-hr/HQ-50K/TRAIN_BICUBIC
--------------------------------------------------------------------------------
RESPONSE 403: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
ERROR CODE: AuthenticationFailed
--------------------------------------------------------------------------------
Response contained no body
--------------------------------------------------------------------------------
.
```

Looking forward to your reply. Thanks a lot.

**Comment by littleYaang** [comment]
Thks for asking! 
We have update the link for azcopy. Pls try again!

**Comment by littleYaang** [comment]
We found that the azcopy links are only valid for a certain period of time, so we provide a more reliable link through BAIDU CLOUD.
